/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import javax.tools.StandardJavaFileManager;
import java.util.Random;

public class App {

    public static void main(String[] args) {

        char[][] tabuleiro = new char[10][10];
        inicializar_tabuleiro(tabuleiro);

        posicionar_navio_tabuleiro(tabuleiro, 5, 'P');
        posicionar_navio_tabuleiro(tabuleiro, 4, 'E');
        posicionar_navio_tabuleiro(tabuleiro, 3, 'C');
        posicionar_navio_tabuleiro(tabuleiro, 3, 'S');
        posicionar_navio_tabuleiro(tabuleiro, 2, 'N');

        imprimir_tabuleiro(tabuleiro);

    }

    public static void posicionar_navio_tabuleiro(char[][] tabuleiro, int tamanho, char simbolo) {
        Random rand = new Random();
        boolean posicionado = false;

        while (!posicionado) {
            boolean vertical = rand.nextBoolean();
            int linha = rand.nextInt(10);
            int coluna = rand.nextInt(10);

            if (pode_inserir(tabuleiro, linha, coluna, tamanho, vertical)) {
                for (int i = 0; i < tamanho; i++) {
                    if (vertical)
                        tabuleiro[linha + i][coluna] = simbolo;
                    else
                        tabuleiro[linha][coluna + i] = simbolo;
                }
                posicionado = true;
            }
        }
    }
    // Verifica se é possível inserir o navio na posição desejada
    public static boolean pode_inserir(char[][] tabuleiro, int linha, int coluna, int tamanho, boolean vertical) {
        if(vertical) {
            if (linha + tamanho > 10) return false;
            for (int i = 0; i < tamanho; i++) {
                if (tabuleiro[linha + i][coluna] != '.') return false;
            }
        } else {
            if (coluna + tamanho > 10) return false;
            for (int i = 0; i < tamanho; i++) {
                if (tabuleiro[linha][coluna] != '.') return false;
            }
        }
        return true;
    }

    // vai inicializar o tabuleiro com pontos
    public static void inicializar_tabuleiro(char[][] tabuleiro) {
        for (int i = 0; i < 10; i++)
            for (int j = 0; j < 10; j++)
                tabuleiro[i][j] = '.';
    }

    // imprime o tabuleiro todo formatado
    public static void imprimir_tabuleiro(char[][] tabuleiro) {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                System.out.print(tabuleiro[i][j] + " ");
            }
            System.out.println();
        }
    }
}

